### ISSUE TITLE
Would you like to support Japanese?

### ISSUE THREAD

**Issue by AngelSeed** [Mor3x/Wipe-Clipper#4]
I think it's very convenient and I want to use it, but it's not supported, so I hope that you can also support Japanese.

**Comment by Mor3x** [comment]
Ah, missed that one, thank you for requesting!

Plugin already updated and the new version can be [downloaded here.](https://github.com/Mor3x/Wipe-Clipper/releases/tag/v1.03.3)

**Comment by AngelSeed** [comment]
Oh oh ~~
thank you! !! It really helps! !!
